### PR TITLE
Chunks schedule

### PR DESCRIPTION
**Pull request by abmantz**
moved to chunks/README.md from ./index.ipynb, as we discussed

### CODE REVIEW

**Comment by abmantz** [comment]
Thanks, I'd missed those.

**Review by drphilmarshall — COMMENTED** [review]
We can go with this, but the markdown only renders well when the course is viewed on GitHub. The index.ipynb provided a list of hyperlinks whether it was viewed locally or online. As long as the classroom has wifi and we are connected to it, it shouldn't matter. (We solved this problem last year: the top level file for navigating the course was an IPython notebook.)

**Comment by abmantz** [comment]
Crap, I forgot that notebook doesn't render pure markdown. What a pain in the butt.

In this one case, though, I really like the convenience of having README.md display automatically in github when we navigate to the chunks folder.

**Review by drphilmarshall — APPROVED** [review]
OK, looks good

**Pull request merged**
