### PR TITLE
Straight line fit, inference approaches, Cepheids data chunk

### PR DESCRIPTION
**Pull request by drphilmarshall**
@abmantz This is all for Thursday Jan 19th, in response to #95 - I decided I wanted to go through the straight line fit as a worked example, using the Cepheids dataset as motivation/inspiration. This means I'll start with a data chunk about the dataset, and then move onto a Bayesian inference of the parameters of a power law model for P and L. My plan is then to follow it up with a separate notebook on approaches to inference, answering the question "what just happened? and how is it like maximum likelihood or least squares?!" I'll shout when it's ready to review but feel free to browse any time, of course.

### CODE REVIEW

**Comment by abmantz** [comment]
I don't entirely see the logic behind what you're planning yet, but a couple issues:
1. The SDSS data chunk needs to be done *this week* for HW reasons, so it would be much better to use that throughout if possible. It's unlikely that all 4 chunks you've proposed here will be finished.
2. The non-uniform slope prior presumably makes the posterior non-Gaussian, contrary to your conclusions slide. It also obfuscates the connection to least squares...

**Comment by drphilmarshall** [comment]
The bivariate Gaussian note was vestigial, thanks for catching that. The logic was to carry out a Bayesian inference example following on from the bayes_theorem theory chunk, following the general approach that we've been building up. The follow-up chunk will be about the connections to maximum likelihood and least squares. I think it's better to see these methods _after_ the more generalizable Bayesian solution. The approaches/comparison/philosophy chunk will probably need to be done in next Tuesday's class.

The two dataset chunks, cepheids and SDSS, are both pretty quick: removing one of them would probably only save 5 mins I think. Going through the homework will be fairly fast this week as well: 10-15 mins. How about we see how far we get this afternoon, and then I either a) rework the HW problem to use the Cepheids data, or b) rework the straight line chunk to use the SDSS data? I'm leaning towards a) right now, but TBH it'd be best if we can use both datasets I think, for variety.

**Comment by abmantz** [comment]
My comment was based on the fact that we planned on using Cepheids later. In principle, any data that have a trend would work in either case, but it seems better to stick with one in a given week.

**Comment by abmantz** [comment]
Add https://arxiv.org/abs/1411.5018 as reading?

**Pull request merged**
