### PR TITLE
A Short Tour of an Astronomical Inference

### PR DESCRIPTION
**Pull request by drphilmarshall**
@abmantz I think I like [Mantz et al 2016](https://arxiv.org/abs/1509.01322) ("Cosmology and Astrophysics from Relaxed Galaxy Clusters III: Thermodynamic Profiles and Scaling Relations") for our initial tour, because it links well the pixel-level analysis that I think we should start with to a population analysis based on summaries/measurements. I've laid out the chunk in [tour.ipynb](https://github.com/KIPAC/StatisticalMethods/blob/issue/88/tour/chunks/tour.ipynb), and am now just filling in images from the paper with commentary. I think this will work well as an introduction (well done, past Adam and Phil :-)): the class will briefly hear lots of concepts that we then return to throughout the rest of the course. 

Let me know what you think while I fill in the remaining gaps! A second active learning activity could be in order, for example.

This is in response to #88

### CODE REVIEW

**Comment by abmantz** [comment]
Probably best to talk this over in person later today. Very quickly:

The current discussion point strikes me as too vague for 5 min, but is good for getting immediate answers (as I think we did last year).

We are clearly following different conventions for where to keep graphics. I think it makes more sense to migrate everything that gets shown in a chunk into the graphics/ folder, along with the code that creates them whenever possible. For images in the repo that we didn't create (in repo'ed code), I suggest adding a .source file, e.g. this one that is not yet committed:

missing_malquist.source
```
Wikimedia Commons
https://commons.wikimedia.org/wiki/File:Bias2.png

Summary
Description 	English: my second attempt an showing the malmquist bias
Date 	
Source 	Own work
Author 	Galaxy1F10

Licensing
Public domain
I, the copyright holder of this work, release this work into the public domain. This applies worldwide.
In some countries this may not be legally possible; if so:
I grant anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.
```

**Comment by abmantz** [comment]
Also, to illustrate the steps you laid out will probably require drawing from papers I and II as well. Not a big deal, but just to warn you.

**Comment by abmantz** [comment]
As mentioned yesterday, the (incorrect) background image should be removed.

wrt this statement
>Predictions of X-ray images (left) need to include variable effective exposure time and point source masking (center), and particle background (right).
To predict the whole image, point sources actually shouldn't be masked. You should either mask the "data" image or remove the mask from the exposure map. Depends how accurate you want to be.

Also depending how much detail you want, keep in mind that we don't actually fit the 2D image data in the deprojection analysis. It's effectively a 1D (spatial) fit to 1D spectra.

*Checking the cluster models* - I can give you a plot showing a fitted spectrum and residuals (most easily for a different cluster, but who cares). I also think you're confused here - the "very flexible" model is the one that you described above. The blue model is from the HSE fit, which isn't described until later.

It might make more sense to describe both types of fit under "Modelling...", removing the profiles figure from there. Then "checking" includes both a new spectrum plot and the comparison of profiles. Then, on to summarizing, where the N photons that became M spectra are reduced to a couple of numbers.

If sufficiently encouraged, I could make a scaling plot without the fit results on it, for the summarizing slide. Then the one with the fit corresponds to "checking the population model".

**Comment by drphilmarshall** [comment]
@abmantz Thanks for the feedback. I think a plot showing the fit to the spectrum could be helpful, yeah - but we could also go with what I have here. I put in a second short exercise, to help make the point that inference and measurement are the same thing (I'm asking them to identify assumptions that they make implicitly when measuring their own height). Merge if you're happy with it!

**Comment by abmantz** [comment]
Seeing how you're still giving the impression that the fit is to imaging data, adding a spectrum/residual plot as is would just be confusing.

**Comment by drphilmarshall** [comment]
Ah - thanks, I just added a slide pointing out the annular binning. I think the slides are now consistent (I had said earlier that this summarizing was going to happen). I think we can go either with or without a residual plot - if its to hand, great, otherwise, no worries!

**Pull request merged**
