### PR TITLE
2017 branch merge

### PR DESCRIPTION
**Pull request by abmantz**
Need to do this before first class. (Ideally, before first email to students encouraging them to set up git.)

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Good call. I'm thinking of renaming "lessons" to "attic" (as in, "don't
look in the attic"). The examples can stay as they are I think: I'm already
planning on linking to bits and pieces there directly.

**Comment by abmantz** [comment]
I would suggest moving everything not currently used to the attic (things can always be moved back later). Either way, you'll have to handle this since I don't know what files you depend on (I have no dependencies in the old directory structure).

**Comment by drphilmarshall** [comment]
OK, I've left the `examples` folder where it is, and moved `notes`, `lesson` and `scikit-learn` into `.archive/2015`. I think this is clean enough. Next, I'll draft an email to the group for you to edit.

**Comment by abmantz** [comment]
Note that #69 has not been fixed in the example notebooks.

**Comment by drphilmarshall** [comment]
Yeah - nor the mechanize/astroquery issue #63 

PR with email text in it is #117, for your review!

**Comment by drphilmarshall** [comment]
So, I think the documentation epic #106 can be closed once we have double checked that all our docs and links are in order. I'll take a look while you work on the email.

**Comment by drphilmarshall** [comment]
OK, I'm going to merge this - I think it's good enough for the first email. Thanks for all the edits! :-)

**Pull request merged**
