### PR TITLE
Added notes on optimization, frequentist uncertainties

### PR DESCRIPTION
**Pull request by drphilmarshall**
@abmantz See what you think: I added a tiny `scipy.optimize` demo to the "approaches" chunk to show how MLEs can be computed numerically, and provided some (although admittedly not much) guidance on computing uncertainties.

### CODE REVIEW

**Review by abmantz — APPROVED** [review]
I would add the usual table of delta-chisquares for different #s of parameters to make explicit the link to what they've seen before.

Frequentists have an answer for how to account for nuisance parameters. You maximize the likelihood over them.

It's not the case that frequentist computations are less expensive if you want to get confidence regions. You might be conflating frequentism with the Laplace approximation too much. A better frequentist would actually look for the delta-chisquare envelope in parameter space, which is heinously more expensive than MCMC. An even better one would probably generate loads of fake data to characterize their estimator.

I disagree with the definition of "best fit" that you're pushing. Obviously all non-Bayesian papers adopt it, and they are more numerous. So it's a true statement that it "usually" means max like, but only because most authors historically have never thought twice about it.

I don't personally think that any of the code exposed here is helpful. It just makes the notes more difficult to read.

**Comment by drphilmarshall** [comment]
Thanks! I added a slide on delta chi-sq, but I drew the line at providing a table - I put in a line of code instead.  It is useful to see code, even if its pointing at a packaged function: it demystifies the process, and provides starting points for other applications (like homework problems!). 

With the final bullet points, I agree that the answers are ambiguous! Let's try and give both sides an airing in class. 

Regarding the use of the term "best fit": would you not say that it is generally understood to refer to the prediction that _most closely matches the observed data_? ie The one that "goes through the points" best? I would. If I then assign a prior that regularizes the fit, by pulling the model predictions away from the observations, wouldn't we say that the "goodness of fit" has decreased?  I think we would. It seems to me that if I were to try to reclaim the term "best fit" from its historical useage in astronomy, I stand a high chance of being misunderstood... So I've ended up reserving the term "best fit" for maximum likelihood, and I use "most probable" for the peak of the posterior PDF - and have found it helpful to retain this distinction.

**Comment by abmantz** [comment]
> Thanks! I added a slide on delta chi-sq, but I drew the line at providing a table - I put in a line of code instead. It is useful to see code, even if its pointing at a packaged function: it demystifies the process, and provides starting points for other applications (like homework problems!).

I think it would help to spell out where the $N\sigma$ terminology comes from, i.e. with reference to a univariate Gaussian. Then your code snippet is more correctly and transparently written as the python equivalent of
```
qchisq(pchisq(1, df=1), df=2)
```
or more generally
```
sigmas = 1
D = 2
qchisq(pchisq(sigmas^2, 1), D)
```

> "best fit"

It's not a big stretch to interpret "best fit" as the best fit to all the input information, including the prior (which might itself be determined from external data). Similarly, "goodness of fit" requires us to specify what particular data set or information we're judging by, and can reasonably mean the data and prior together. I don't believe that this is a case of "taking back" the terminology. Just as "fit" is commonly used to mean any process for estimating good parameter values and their uncertainties, "best fit" is commonly used to mean the reported estimate from that process, regardless of which it was.

**Comment by drphilmarshall** [comment]
Good - I like the "best fit to _all_ data" argument. Let's point out the variety of uses of best fit as well, then. Thanks!

I fixed up the notes on delta chisq, and re-ordered a bit. I think this is good to go now

**Comment by drphilmarshall** [comment]
If only I had merged this *before* class... Oh well - it works now, for next time.

**Pull request merged**
