### PR TITLE
fix the bug and use better coding style in XrayImage/Summarizing.ipynb

### PR DESCRIPTION
**Pull request by yymao**

### CODE REVIEW

**Comment by abmantz** [comment]
[22] looks like it introduces a new bug?
Also, github doesn't give us a diff of the notebook file, unless I'm missing something, so please be more specific in describing the changes.

**Comment by yymao** [comment]
Fix the diff issue. you can now see the changes.

What's the bug you spot in [22]? It works for me. 

Instead of modify the image values, this new approach uses "bool flags" to slice background and single, make the code more readable and robust.

**Comment by abmantz** [comment]
Ah, I was just basing that on the plotted image, which appears to be the
reverse of what Phil showed in lecture. At first glance, the actual code
looks ok for what it's used for later. It would be good to fix the visual,
though.

**Comment by drphilmarshall** [comment]
Thanks @yymao ! I put the view of the annulus back in (I use "masked image" to mean "an image where you only see the pixels of interest", which in this case meant the annulus I was using to estimate the background. The counts come out more sensibly now, although still way too high (because the mean is not a good measure when you have left a point source in the background region ;-) )

**Comment by yymao** [comment]
Cool. One small note, the code

``` python
maskedimage[signal] = -1
maskedimage[outskirts] = -1
```

can be written as

``` python
maskedimage[~background] = -1
```

This is slightly more readable because it reads "setting all non-background pixels to -1". 

Similarly, later in the notebook, 

``` python
maskedimage[background] = 0
maskedimage[outskirts] = 0
```

can be shorten to

``` python
maskedimage[~signal] = 0
```

which sets all non-signal pixels to 0

**Comment by drphilmarshall** [comment]
Yeah, I saw that - it's nice, but not as "literate" as my version. (Also,
the "~" operator looks like "approximately" rather than "not"...  I know
you just have to learn these things, but to keep things clear I went with
the longer, more readable version. I'll remember the "~" for later though -
thanks! :-) )

**Comment by yymao** [comment]
I agree that it is not clear at the first sight that `~` means "not". If this is the main reason for not using the short version, we can write

``` python
maskedimage[np.logical_not(background)] = -1
```

The reason I think this would be better is that, in the longer version, when the definition of "background" changes, one has to make sure that "signal" and "outskirts" are also changed accordingly. In my opinion, this kind of situation should be avoided whenever possible as it could easily become a bug.

**Comment by drphilmarshall** [comment]
Agreed! I like that `np.logical_not()` call :-) Updating!

**Pull request merged**
