### PR TITLE
Slides on course content/focus

### PR DESCRIPTION
**Pull request by drphilmarshall**
Se what you think, @abmantz - this is in response to #87

### CODE REVIEW

**Comment by drphilmarshall** [comment]
PS. They are strongly based on the "goals" listed on our README.

**Comment by abmantz** [comment]
I actually think we should try to finagle more about time series and categorical data into the course somewhere (maybe problems). But otherwise, this looks fine to me.

**Comment by abmantz** [comment]
(what we say is probably more important than what's on the slides here)

**Comment by drphilmarshall** [comment]
Yeah. I tweaked that sentence off, and will now merge. Thanks!

**Pull request merged**
